swagger: '2.0'
info:
  description: |
    GoDC - Kopral APIs
  version: 1.0.0
  title: Kopral
tags:
- name: kopral
  description: CRUD operations on kopral APIs
schemes:
- http
basePath: /v1/api
paths:
  /stats/node:
    get:
      tags:
      - kopral
      summary: Show stats of node where kopral is running on
      operationId: getNodeStats
      produces:
      - application/json
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/NodeStats'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
definitions:
  NodeStats:
    type: object
    required:
      - cpu
      - memory
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      cpu:
        type: integer
        format: uint64
      memory:
        type: integer
        format: uint64
  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string