---
swagger: "2.0"
info:
  description: "GoDC API"
  version: "0.1.0"
  title: "GoDC"
basePath: "/api/v1"
tags:
- name: "cluster"
- name: "vm"
schemes:
- "http"
produces:
- "application/json"
paths:
  /clusters:
    get:
      tags:
      - "cluster"
      summary: "List all Kubernetes clusters"
      operationId: "listClusters"
      parameters: []
      responses:
        200:
          description: "Listed successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Cluster"
  /clusters/{clusterName}:
    get:
      tags:
      - "cluster"
      operationId: "getCluster"
      parameters:
      - name: "clusterName"
        in: "path"
        description: "The Kubernetes cluster name"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Cluster"
  /vms:
    get:
      tags:
      - "vm"
      summary: "List all virtual machines"
      operationId: "listVms"
      parameters: []
      responses:
        200:
          description: "Listed successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Vm"
  /vms/{vmName}:
    get:
      tags:
      - "vm"
      operationId: "getVm"
      parameters:
      - name: "vmName"
        in: "path"
        description: "The virtual machine name"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Vm"
definitions:
  ClusterParameters:
    type: "object"
    required:
    - "kubernetes_master_host"
    properties:
      kubernetes_master_host:
        type: "string"
      kubernetes_worker_instances:
        type: "integer"
        minimum: 1
        maximum: 50
  Cluster:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      kubernetes_master_ips:
        type: "array"
        items:
          type: "string"
      parameters:
        $ref: "#/definitions/ClusterParameters"
  VmParameters:
    type: "object"
    required:
    - "ip"
    - "host"
    properties:
      ip:
        type: "string"
      host:
        type: "string"
  Vm:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
      parameters:
        $ref: "#/definitions/VmParameters"
